export enum ENV {
  JWT_TOKEN_ACCESS_SECRET = 'JWT_TOKEN_ACCESS_SECRET',
  JWT_TOKEN_ACCESS_SECRET_EXP = 'JWT_TOKEN_ACCESS_SECRET_EXP',
  JWT_TOKEN_REFRESH_SECRET = 'JWT_TOKEN_REFRESH_SECRET',
  JWT_TOKEN_REFRESH_SECRET_EXP = 'JWT_TOKEN_REFRESH_SECRET_EXP',
  DATABASE_URL = 'DATABASE_URL',

  REDIS_HOST = 'REDIS_HOST',
  REDIS_PORT = 'REDIS_PORT',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
}
